language: python
python:
- '3.6'
before_install:
- pip install poetry
install:
- poetry install -v
script:
  - echo "No tests to run"
deploy:
  provider: script
  script: poetry publish --build -u __token__ -p $PYPI_TOKEN
  on:
    tags: true
